apiVersion: apps/v1 # Especifica a versão da API do Kubernetes
kind: DaemonSet # Define o tipo de recurso como DaemonSet
metadata: # Metadados do DaemonSet
  labels: # Rótulos associados ao DaemonSet
    app: node-exporter-daemonset # Rótulo para identificar o aplicativo
  name: node-exporter-daemonset # Nome do DaemonSet
  namespace: day-4 # Namespace onde o DaemonSet será criado
spec: # Especificações do DaemonSet
  selector: # Seletor para identificar os Pods gerenciados pelo DaemonSet
    matchLabels: # Rótulos que os Pods devem ter para serem gerenciados por este DaemonSet
      app: node-exporter-daemonset # Rótulo correspondente aos Pods
  template: # Template para os Pods criados pelo DaemonSet
    metadata: # Metadados dos Pods
      labels: # Rótulos associados aos Pods
        app: node-exporter-daemonset # Rótulo para identificar o aplicativo
    spec: # Especificações dos Pods
      hostNetwork: true # Permite que os Pods usem a rede do host
      containers: # Definição dos contêineres dentro dos Pods
        - image: prom/node-exporter:latest # Imagem do contêiner do Node Exporter
          name: node-exporter # Nome do contêiner
          ports: # Portas expostas pelo contêiner
            - containerPort: 9100 # Porta padrão do Node Exporter
              hostPort: 9100 # Porta no host onde o contêiner estará acessível
          volumeMounts: # Montagens de volume para o contêiner
            - name: proc # Nome do volume
              mountPath: /host/proc # Caminho onde o volume será montado no contêiner
              readOnly: true # Montagem somente leitura
            - name: sys
              mountPath: /host/sys
              readOnly: true
      volumes: # Definição dos volumes para os Pods
      - name: proc # Nome do volume
        hostPath: # Tipo de volume que monta um diretório do host
          path: /proc # Caminho no host a ser montado
      - name: sys
        hostPath:
          path: /sys
