apiVersion: v1
kind: Pod
metadata:
  name: pod-secret
spec:
  containers:
    - name: secret-container
      image: nginx
      env:
      - name:  USERNAME
        valueFrom:
          secretKeyRef:
            name: secret-cli
            key: username
      - name: PASSWORD
        valueFrom:
          secretKeyRef:
            name: secret-cli
            key: password
